using HIV_System_API_BOs;
using HIV_System_API_DTOs.AccountDTO;
using HIV_System_API_DTOs.DoctorDTO;
using HIV_System_API_DTOs.DoctorWorkScheduleDTO;
using HIV_System_API_Repositories.Implements;
using HIV_System_API_Repositories.Interfaces;
using HIV_System_API_Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HIV_System_API_Services.Implements
{
    public class DoctorService : IDoctorService
    {
        private readonly IDoctorRepo _doctorRepo;
        private readonly IDoctorWorkScheduleRepo _workScheduleRepo;
        public DoctorService()
        {
            _doctorRepo = new DoctorRepo();
            _workScheduleRepo = new DoctorWorkScheduleRepo();
        }

        private Doctor MapToEntity(DoctorRequestDTO dto)
        {
            if (dto == null) throw new ArgumentNullException(nameof(dto));

            return new Doctor
            {
                AccId = dto.AccId,
                Degree = dto.Degree,
                Bio = dto.Bio
                // DctId is not set here, as it's usually generated by the database
                // Navigation properties (Account, Appointments, DoctorWorkSchedules) are not set here
            };
        }

        private DoctorResponseDTO MapToResponseDTO(Doctor doctor)
        {
            if (doctor == null) throw new ArgumentNullException(nameof(doctor));

            var workSchedules = doctor.DoctorWorkSchedules?
                .Select(ws => new DoctorWorkScheduleResponseDTO
                {
                    DwsId = ws.DwsId,
                    DctId = ws.DoctorId,
                    DayOfWeek = ws.DayOfWeek ?? 0,
                    StartTime = ws.StartTime,
                    EndTime = ws.EndTime
                }).ToList() ?? new List<DoctorWorkScheduleResponseDTO>();

            return new DoctorResponseDTO
            {
                DctId = doctor.DctId,
                Degree = doctor.Degree,
                Bio = doctor.Bio,
                AccId = doctor.AccId,
                Account = new AccountResponseDTO
                {
                    AccId = doctor.Account.AccId,
                    AccUsername = doctor.Account.AccUsername,
                    AccPassword = doctor.Account.AccPassword,
                    Email = doctor.Account.Email,
                    Fullname = doctor.Account.Fullname,
                    Dob = doctor.Account.Dob,
                    Gender = doctor.Account.Gender,
                    Roles = doctor.Account.Roles,
                    IsActive = doctor.Account.IsActive
                },
                WorkSchedule = workSchedules
            };
        }

        public async Task<DoctorResponseDTO> CreateDoctorAsync(DoctorRequestDTO doctor)
        {
            if (doctor == null) throw new ArgumentNullException(nameof(doctor));

            // Map DTO to entity
            var doctorEntity = MapToEntity(doctor);

            // Create doctor in repository
            var createdDoctor = await _doctorRepo.CreateDoctorAsync(doctorEntity);

            // Fetch the full doctor entity with navigation properties (e.g., Account)
            var fullDoctor = await _doctorRepo.GetDoctorByIdAsync(createdDoctor.DctId);
            if (fullDoctor == null)
                throw new InvalidOperationException("Failed to retrieve the created doctor.");

            // Map to response DTO
            return MapToResponseDTO(fullDoctor);
        }

        public async Task<bool> DeleteDoctorAsync(int id)
        {
            // Call the repository to delete the doctor by id
            return await _doctorRepo.DeleteDoctorAsync(id);
        }

        public async Task<List<DoctorResponseDTO>> GetAllDoctorsAsync()
        {
            var doctors = await _doctorRepo.GetAllDoctorsAsync();
            var result = new List<DoctorResponseDTO>();

            foreach (var doctor in doctors)
            {
                // Defensive: skip if Account is null (should not happen if DB is correct)
                if (doctor.Account == null)
                    continue;

                result.Add(MapToResponseDTO(doctor));
            }

            return result;
        }

        public async Task<DoctorResponseDTO?> GetDoctorByIdAsync(int id)
        {
            // Fetch the doctor entity by id from the repository
            var doctor = await _doctorRepo.GetDoctorByIdAsync(id);

            // If not found or Account navigation property is null, return null
            if (doctor == null || doctor.Account == null)
                return null;

            // Map to response DTO
            return MapToResponseDTO(doctor);
        }

        public async Task<DoctorResponseDTO?> UpdateDoctorAsync(int id, DoctorRequestDTO doctor)
        {
            if (doctor == null) throw new ArgumentNullException(nameof(doctor));

            // Fetch the existing doctor entity
            var existingDoctor = await _doctorRepo.GetDoctorByIdAsync(id);
            if (existingDoctor == null)
                return null;

            // Update properties
            existingDoctor.Degree = doctor.Degree;
            existingDoctor.Bio = doctor.Bio;
            existingDoctor.AccId = doctor.AccId;

            // Update in repository
            var updatedDoctor = await _doctorRepo.UpdateDoctorAsync(id, existingDoctor);
            if (updatedDoctor == null)
                return null;

            // Fetch the full doctor entity with navigation properties (e.g., Account)
            var fullDoctor = await _doctorRepo.GetDoctorByIdAsync(updatedDoctor.DctId);
            if (fullDoctor == null || fullDoctor.Account == null)
                return null;

            // Map to response DTO
            return MapToResponseDTO(fullDoctor);
        }
    }
}
